[package]
description = "Extract Mindful Sessions from your Apple Health export data for use by Bloom"
name = "bloom-parse"
version = "0.1.2"
edition = "2024"
build = "build.rs"

[package.metadata.winresource]
LegalCopyright = "Copyright © 2024 Meditation Mind"
OriginalFilename = "bloom-parse.exe"

[dependencies]
csv = "1.3.0"
quick-xml = { version = "0.40.0", features = ["serialize"] }
serde = { version = "1.0.210", features = ["derive"] }
tinyfiledialogs = "3.9.1"

[dependencies.chrono]
version = "0.4.44"
default-features = false
features = ["std", "serde"]

[build-dependencies]
winresource = "0.1"
